### PR TITLE
Allow exporting books and modules

### PR DESCRIPTION
**Pull request by PiotrKozlowski**
There is new permission `content:export` which is required for users to be able to export content:
obraz

On book screen there is new button `Export`: (Button is visible only for users with permission `content:export`)
obraz

Same button is visible in module preview and on module screen:
obraz

obraz

Clicking on button will open new tab which will be closed when downloading file will start. Saving file is handled by browser.

### CODE REVIEW

**Comment by PiotrKozlowski** [comment]
@paulinaszczucinska Are we sticking to the option that only process manager can export zip files for modules / books or not?
cc @aiwenar

**Comment by paulinaszczucinska** [comment]
Is it possible to make it a permission which can be added to a role? As I said, I would not like any team member export entire zip which is not final. However, I can imagine that in smaller teams such restrictions might be too strong and unnecessary. 
If it cannot be flexibly composed in a role’s permissions by manager, I would allow export/import Process manager and help desk.

**Comment by PiotrKozlowski** [comment]
Yes, by referring to "process manager" I was thinking about users with permission `editing-process:manage`. Other permissions are:
'member:add', 'member:remove',
'member:assign-role',  'member:edit-permissions',
'role:edit' | 'book:edit', 'module:edit',
'editing-process:edit', 'editing-process:manage',
'resources:manage'

**Comment by MartaSztuka** [comment]
User with permission to export books can see the button and export book.
Screenshot from 2019-12-04 14-06-05
Screenshot from 2019-12-04 14-05-43

**Pull request merged**
