### PR TITLE
Unify inserting docrefs, links and xrefs

### LINKED ISSUE #214: Better UI for inserting links
There should be only one UI element for inserting all types of hyperlinks: `xref`, `docref`, `link`

### PR DESCRIPTION
**Pull request by PiotrKozlowski**
close #214 

### Now there is only one button for inserting links:
obraz

### If we select some text in editor and click it new window will be opened and `Provide text` will be propagated with selected text:
obraz

### <kbd>Insert link</kbd> will be active only in 3 cases:
1. When url and text is provided
2. When reference element is provided
3. When reference document and text are provided

### Case 1:
obraz

### Case 2: (when reference element is selected then input for url and text are disabled)
obraz

### Case 3: (when document is selected then input for url is disabled and text input will be replaced with document title - it can still be changed)
obraz

### Additional features:
When text and url inputs are empty and user start writing url then text input will be automatically updated to url value - it can be still changed to something else
obraz

### CODE REVIEW

**Comment by aiwenar** [comment]
You should have to choose the type of the link first - for example by selecting one of three tabs for one of three types of links we have. As it is now the user is first prompted to enter link and title, bot of which will then be removed if they select to create a cross-reference.

**Comment by PiotrKozlowski** [comment]
After changes adding link will open standard xref selector modal with additional new tab:
obraz

**Comment by MartaSztuka** [comment]
Works good.
Screenshot from 2019-12-16 12-19-29

**Comment by MartaSztuka** [comment]
Tested on staging - all good.
Screenshot from 2020-01-07 10-37-19

**Pull request merged**
